import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-secondary-900 text-gray-300'>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
